[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "adcirc-view"
version = "0.0.1"
authors = [
  { name="Namo Wichitrnithed", email="namo26june@pm.me" },
]
description = "A tool to compare ADCIRC outputs"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
"numpy",
"matplotlib"
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.scripts]
adcirc-view = "adcirc_view.cli:main"

[project.urls]
Homepage = "https://github.com/namo626/adcirc-view"
